name: Deploy Edge Impulse Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout firmware source code
        uses: actions/checkout@v3

      - name: Build and deploy Edge Impulse Model
        uses: edgeimpulse/build-deploy@v1
        id: build-deploy-arduino
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          api_key: ${{ secrets.API_KEY }}
          #'deployment_type: "arduino"

      - name: Extract the Model and SDK
        run: |
          mkdir temp
          unzip -q "${{ steps.build-deploy.outputs.deployment_file_name }}" -d temp
          mv temp/edge-impulse-sdk/ .
          mv temp/model-parameters/ .
          mv temp/tflite-model/ .
          rm -rf "${{ steps.build-deploy.outputs.deployment_file_name }}"
          rm -rf temp/    
